version: '3.7'

services:

  cw-postgres:
    image: postgres:latest
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=cryptodb"
    ports:
      - 45432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  cw-cryptopocket:
    image: agostinaluciano/crypto-pocket
    environment:
      - "IP=cw-postgres"
      - "PORT=5432"
      - "USERNAME=root"
      - "PASSWORD=root"
      - "COINMARKETCAP_API_KEY=<<your>>"
      - "COINMARKETCAP_URL=https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest"
      - "BD=cryptodb"
    ports:
      - 8080:8080
    depends_on:
      - cw-postgres
