DROP TABLE IF EXISTS "users";

CREATE TABLE IF NOT EXISTS "users" (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  enabled BOOLEAN DEFAULT TRUE
);

DROP TABLE IF EXISTS "cryptocurrency";

CREATE TABLE IF NOT EXISTS "cryptocurrency" (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  symbol VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS "transaction";

CREATE TABLE IF NOT EXISTS "transaction" (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INTEGER NOT NULL,
  crypto_currency_id INTEGER NOT NULL,
  amount NUMERIC(22,0) NOT NULL,
  operation_type VARCHAR(50) NOT NULL,
  transaction_date VARCHAR(255) NOT NULL,
  CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES "users"(id),
  CONSTRAINT fk_cryptocurrency FOREIGN KEY(crypto_currency_id) REFERENCES "cryptocurrency"(id)
);

INSERT INTO "cryptocurrency" (name, symbol) VALUES
('Bitcoin',	'BTC'),
('Ethereum',	'ETH'),
('Tether',	'USDT'),
('XRP',	'XRP'),
('Polkadot',	'DOT'),
('Cardano',	'ADA'),
('Chainlink',	'LINK'),
('Litecoin',	'LTC'),
('Binance Coin',	'BNB'),
('Bitcoin Cash',	'BCH'),
('Stellar',	'XLM'),
('Dogecoin',	'DOGE'),
('USD Coin',	'USDC');

INSERT INTO "users" (username, password, email) VALUES
('freeman.mohr',	'0l6lyyy8x',	'Romana.Pagac@gmail.com'),
('tobias.shields',	's26i95xz49e4ko',	'Lasandra.Ward@gmail.com'),
('houston.luettgen',	'lkf9ttsxcy',	'Virgilio.Miller@gmail.com'),
('gladis.trantow',	'fcq9s1rmg',	'Colby.Wiza@gmail.com'),
('anita.flatley',	'3y23lwum',	'Clinton.Douglas@gmail.com'),
('belva.nitzsche',	'xrqgmnocosaqm',	'Reynalda.Simonis@gmail.com'),
('modesto.tromp',	'bw8n3cf9',	'Cristobal.Kub@gmail.com'),
('delcie.beatty',	'gb3uyxo4pmk9',	'Renato.Gerlach@gmail.com'),
('harris.heller',	'szzrv2defr',	'Hayden.Goyette@gmail.com'),
('victor.block',	'1ywk3oqq',	'Logan.Toy@gmail.com'),
('bobbi.grady',	'8yas0ov2scd',	'Laurence.Rosenbaum@gmail.com'),
('rosanna.leffler',	'9bvm81mkg',	'Ellsworth.Robel@gmail.com'),
('claud.cole',	'pnysduri10r5',	'Versie.Morar@gmail.com'),
('wilbert.spencer',	'1tcw01j6m',	'Curt.Leannon@gmail.com'),
('jody.daniel',	'avb30s61lwkg',	'Brice.Bergnaum@gmail.com'),
('marg.wiza',	'uas1ap2r4xl5',	'Clair.Welch@gmail.com'),
('kaylene.witting',	'bkgxa04sr7ed',	'Soon.Cole@gmail.com'),
('merlene.weimann',	'fd4e1lekm9xiw2',	'Colton.Rogahn@gmail.com'),
('russel.quitzon',	'logsrv9xpp',	'Daina.Kuhlman@gmail.com'),
('demetrius.greenfelder',	'eczqsqh4budxle',	'Michaela.Corkery@gmail.com'),
('denny.bayer',	'arhcaqjd7',	'Cheryll.Borer@gmail.com'),
('gearldine.robel',	'tds399v7n',	'Lanora.Runte@gmail.com'),
('richard.leannon',	'2cfiw7zt2v',	'Josiah.O''Connell@gmail.com'),
('dorsey.satterfield',	'mfxzhp3231q3z2c',	'Marceline.Nitzsche@gmail.com'),
('elisabeth.halvorson',	'tdpk0jxbz2st',	'Effie.Harber@gmail.com'),
('fallon.turner',	'55d5z8cv',	'Miles.Konopelski@gmail.com'),
('clemente.krajcik',	'ysie202bxm9owu0',	'Oren.Nikolaus@gmail.com'),
('jean.mraz',	'fjqmql4s',	'Romelia.Zieme@gmail.com'),
('hai.klein',	'uil3l3bng',	'Adeline.Halvorson@gmail.com'),
('yvone.kuhlman',	'odwkq329wmpq',	'Christeen.Kirlin@gmail.com'),
('alex.haag',	'hueh2j2yn5',	'Donnell.Zboncak@gmail.com'),
('krista.hessel',	'f3dcof99hbc',	'Garnet.Gottlieb@gmail.com'),
('alethia.schneider',	'2ugs3t0rc',	'Darcey.Becker@gmail.com'),
('ferdinand.bauch',	'puy7x7kz3t',	'Crista.Moen@gmail.com'),
('trey.abernathy',	'jpom4f25x19',	'Ben.Cremin@gmail.com'),
('rickey.kilback',	'8sdw7o4cor9obkl',	'Shena.Morissette@gmail.com'),
('carlee.rippin',	'mvw1o9sfmhont2',	'Candy.Weimann@gmail.com'),
('eddy.leffler',	'cchggeszk6w0',	'Wilhemina.Marquardt@gmail.com'),
('tanisha.jacobson',	'd9tllti8m5jqo',	'Malorie.Rippin@gmail.com'),
('efren.schaden',	'im958e1y',	'Isiah.Hoppe@gmail.com'),
('clint.bogan',	'ut7smk82nfhld',	'Artie.Fritsch@gmail.com'),
('kim.herzog',	'eaj84aw85ui',	'Katharina.Mraz@gmail.com'),
('virgilio.ondricka',	'v3jnx770rmaskv',	'Tinisha.Deckow@gmail.com'),
('debroah.rath',	'di5zibt6eeono',	'Star.Kohler@gmail.com'),
('meg.barrows',	'u5nd2gzmwzn',	'Donald.Ondricka@gmail.com'),
('bree.terry',	'ycpaiu620qg08',	'Jacques.Bogisich@gmail.com'),
('lesli.kertzmann',	'q5scoutvf04m3g9',	'Antione.Waters@gmail.com'),
('harris.waters',	'vrf4hclmw',	'Rosendo.Jacobi@gmail.com'),
('magan.witting',	'wraf00bxagtm662',	'Andree.Mayer@gmail.com'),
('edison.mraz',	'ox2vmyeufxj8',	'Ngan.Walker@gmail.com'),
('joaquin.denesik',	'jfa3hs3qy',	'Meridith.Gleason@gmail.com'),
('jacki.littel',	'rn3ryupxisuavg',	'Leoma.Keeling@gmail.com'),
('grayce.armstrong',	'ibqalza3psvs',	'Genaro.Doyle@gmail.com'),
('carter.hills',	'4sq3ox409oal',	'Sabrina.Kling@gmail.com'),
('reggie.hirthe',	'2j0bxs1hvzvg1wm',	'Holley.Boyle@gmail.com'),
('bernard.stroman',	'5328isd173g0c95',	'Val.Abbott@gmail.com'),
('monique.mertz',	'tg7953mtq',	'Herbert.Wintheiser@gmail.com'),
('corey.cummerata',	'iebttzxj',	'Julene.Boyle@gmail.com'),
('lorinda.windler',	'yahvq9aq',	'Bernard.Rau@gmail.com'),
('alejandra.hilll',	'zb79kczroxm51c',	'Lula.Boyle@gmail.com'),
('jamika.west',	'jekhea3p1ha',	'Jarred.Kunze@gmail.com'),
('isidro.mraz',	'k46r9kenclep77',	'Jimmy.Abbott@gmail.com'),
('britt.rempel',	'p6qw6138',	'Stacia.Wyman@gmail.com'),
('jocelyn.grimes',	'x176pkj83j',	'Sherrie.Lesch@gmail.com'),
('stanton.raynor',	'0bwai8ak2jbb',	'Jung.Walsh@gmail.com'),
('howard.hoeger',	'91lzg21178rrns',	'Dara.Schimmel@gmail.com'),
('tressa.willms',	'ynlpv87o4u',	'Blanch.Gislason@gmail.com'),
('jenice.jacobson',	'7n7obytvq',	'Georgeanna.Ondricka@gmail.com'),
('noe.yundt',	'c6cogh07ao02',	'Salina.Heathcote@gmail.com'),
('clark.becker',	'7kl454rqn',	'Gregg.Sporer@gmail.com'),
('bridgett.hegmann',	'i4ejb7jiv',	'Maribel.Lesch@gmail.com'),
('marica.block',	'y70l8isaj',	'Dominque.Ankunding@gmail.com'),
('jerrell.hudson',	'intfxyg0tqtklnm',	'Rigoberto.Lesch@gmail.com'),
('kiara.koss',	'ra5y4419k',	'Marlin.Abbott@gmail.com'),
('verdell.keeling',	'5w235265r8g6ps',	'Jeromy.Heller@gmail.com'),
('modesto.heller',	'5xywex1ctuota9',	'Lexie.Lakin@gmail.com'),
('gina.larkin',	'9qzvugg7k',	'Rena.Lubowitz@gmail.com'),
('avelina.damore',	'wnjgydgaazwb0n',	'Lucretia.Boehm@gmail.com'),
('karena.buckridge',	'qipe23tvcs',	'Willis.Abshire@gmail.com'),
('celina.hermiston',	'adma7spn',	'Kendall.Dooley@gmail.com'),
('shirlene.dare',	'xdysxj7x',	'Babette.Kilback@gmail.com'),
('juan.hoppe',	'ygj3sidx',	'Javier.Kuphal@gmail.com'),
('phillip.weimann',	'7rktwi7xc',	'Lea.Wisozk@gmail.com'),
('teri.dach',	'd68vaom3f0ni3',	'Aron.White@gmail.com'),
('marcelo.sawayn',	'3hrkcf6ubidwk5',	'Thaddeus.Farrell@gmail.com'),
('lottie.kautzer',	'm1blbmt9h6wuo6',	'Margarete.Kuphal@gmail.com'),
('tamara.boehm',	'dsnpnc5z',	'Asley.Kertzmann@gmail.com'),
('genaro.batz',	'nsdb1drpk',	'Andre.Champlin@gmail.com'),
('lauren.gerlach',	'fm2izq9cajqq',	'Lonnie.Bogan@gmail.com'),
('valentine.walter',	'wap7lv3ih3izqcl',	'Lakia.Graham@gmail.com'),
('gregory.harvey',	'magvzjbtlkuuw',	'Wiley.Beahan@gmail.com'),
('adalberto.pfannerstill',	'mqcl56y86k139',	'Roberta.Price@gmail.com'),
('ross.mohr',	'gmhisy9v7jj5',	'Jeanmarie.Grimes@gmail.com'),
('abby.mcclure',	'gvi8t20q7e',	'Annalee.McLaughlin@gmail.com'),
('jonna.oconner',	'8tao7j9h9i30ng',	'Alison.Sanford@gmail.com'),
('dannie.larson',	'rap6k0sbwjl',	'Sydney.Schumm@gmail.com'),
('muriel.russel',	'qkjkqhjl8',	'Cyril.Sawayn@gmail.com'),
('harlan.larson',	'mlt6jmns0',	'Winona.Brown@gmail.com'),
('analisa.franecki',	'0snjt0kjg0r5k',	'Latrina.Carter@gmail.com'),
('eric.dietrich',	'mkrwc894nn9ir2',	'Hershel.Adams@gmail.com');